config/routes.rb
Fenrir::Application.routes.draw do
  resources :scroll_tests

  root 'welcome#index'
  get '/serve_image/:filename' => 'images#serve'
  get '/loki' => 'pages#loki'
  get '/heatmap' => 'pages#heatmap'
  get '/test' => 'pages#test'
  get '/automated_feedback' => 'pages#automated_feedback'
  get '/scroll_tests' => 'scroll_tests#index.html.erb'

end

app/models/query.rb
class Query < ActiveRecord::Base
	attr_accessor :output
	validates :method, presence: true
end

app/models/scroll_test.rb
class ScrollTest < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def serve
    path = "#{Rails.root.to_s}/app/assets/images/#{params[:filename]}.jpg"

    send_file( path,
      :disposition => 'inline',
      :type => 'image/jpeg',
      :x_sendfile => true )
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def initialize
		@article = Array.new
	end

	def loki

	end

	def heatmaps

	end

	def automated_feedback

	end

end

app/controllers/scroll_tests_controller.rb
class ScrollTestsController < ApplicationController
  before_action :set_scroll_test, only: [:show, :edit, :update, :destroy]

  # GET /scroll_tests
  # GET /scroll_tests.json
  def index
    #@scroll_tests = ScrollTest.all
    @scroll_tests = ScrollTest.order(:created_at).page(params[:page])
  end

  # GET /scroll_tests/1
  # GET /scroll_tests/1.json
  def show
  end

  # GET /scroll_tests/new
  def new
    @scroll_test = ScrollTest.new
  end

  # GET /scroll_tests/1/edit
  def edit
  end

  # POST /scroll_tests
  # POST /scroll_tests.json
  def create
    @scroll_test = ScrollTest.new(scroll_test_params)

    respond_to do |format|
      if @scroll_test.save
        format.html { redirect_to @scroll_test, notice: 'Scroll test was successfully created.' }
        format.json { render action: 'show', status: :created, location: @scroll_test }
      else
        format.html { render action: 'new' }
        format.json { render json: @scroll_test.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scroll_tests/1
  # PATCH/PUT /scroll_tests/1.json
  def update
    respond_to do |format|
      if @scroll_test.update(scroll_test_params)
        format.html { redirect_to @scroll_test, notice: 'Scroll test was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @scroll_test.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scroll_tests/1
  # DELETE /scroll_tests/1.json
  def destroy
    @scroll_test.destroy
    respond_to do |format|
      format.html { redirect_to scroll_tests_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_scroll_test
      @scroll_test = ScrollTest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def scroll_test_params
      params.require(:scroll_test).permit(:title, :author, :body)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/scroll_tests_helper.rb
module ScrollTestsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Fenrir" %></title>

    

    <%= stylesheet_link_tag    "defaultTheme" %>
    <%= stylesheet_link_tag    "shCore"%>
    <%= stylesheet_link_tag    "demo"%>
    <%= stylesheet_link_tag    "foundation"%>
    <%= stylesheet_link_tag    "dataTables.foundation" %>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "jquery"%>
    <%= javascript_include_tag "jquery.dataTables"%>
    <%= javascript_include_tag "shCore"%>
    <%= javascript_include_tag "demo"%>
    <%= javascript_include_tag "dataTables.foundation"%>
    <%= csrf_meta_tags %>

    <!--<meta name="viewport" content="initial-scale=1.0, maximum-scale=2.0">-->
    </head>

  <body>

    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/pages/automated_feedback.html.erb
<head>
  <title>Fenrir</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
</head>
<body>
  <div class="row first">
    <canvas id="myCanvas" width="578" height="200"></canvas>
    <script>
      var canvas = document.getElementById('myCanvas');
      var context = canvas.getContext('2d');

      // do cool things with the context
      context.font = '40pt Calibri';
      context.fillStyle = 'blue';
      context.fillText('AUTOMATED FEEDBACK', 150, 100);
    </script>
    <%= link_to "home", '/' %> 
  </div>
</body>

app/views/pages/heatmap.html.erb
<head>
  <title>Fenrir</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
</head>
<body>
  <div class="row first">
    <canvas id="myCanvas" width="578" height="200"></canvas>
    <script>
      var canvas = document.getElementById('myCanvas');
      var context = canvas.getContext('2d');

      // do cool things with the context
      context.font = '40pt Calibri';
      context.fillStyle = 'blue';
      context.fillText('HEATMAP', 150, 100);
    </script>
    <%= link_to "home", '/' %> 
  </div>
</body>

app/views/pages/loki.html.erb
<head>
  <title>Fenrir</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
</head>
<body>
  <div class="row first">
    <canvas id="myCanvas" width="578" height="200"></canvas>
    <script>
      var canvas = document.getElementById('myCanvas');
      var context = canvas.getContext('2d');

      // do cool things with the context
      context.font = '40pt Calibri';
      context.fillStyle = 'blue';
      context.fillText('LOKI', 150, 100);
    </script>
    <%= link_to "home", '/' %> 
  </div>
</body>

app/views/scroll_tests/_form.html.erb
<%= form_for(@scroll_test) do |f| %>
  <% if @scroll_test.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@scroll_test.errors.count, "error") %> prohibited this scroll_test from being saved:</h2>

      <ul>
      <% @scroll_test.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/scroll_tests/_scroll_test.html.erb
# app/views/posts/_post.html.erb
      <tr>
        <td><%= edit_scroll_test_path(scroll_test.id)%></td>
        <td><%= link_to "#{scroll_test.author}", edit_scroll_test_path(scroll_test)%></td>
        <td><%= link_to "#{scroll_test.body}", edit_scroll_test_path(scroll_test.body)%></td>
        <td><%= link_to 'Destroy', scroll_test, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>

app/views/scroll_tests/edit.html.erb
<h1>Editing scroll_test</h1>

<%= render 'form' %>

<%= link_to 'Show', @scroll_test %> |
<%= link_to 'Back', scroll_tests_path %>

app/views/scroll_tests/index.html.erb
<body>
  <div class="row first">
    <table class="dataTable">
      <thead>
        <tr>
          <th>ID</th>
          <th>Title</th>
          <th>Author</th>
          <th>Body</th>
        </tr>
      </thead>

      <tbody>
        <% @scroll_tests.each do |scroll_test| %>
          <%= form_for(scroll_test) do |f| %>
          <tr>
            <td><%= scroll_test.id %></td>
            <td class="field"><%= f.text_field :title, {:onkeyup=>"if (event.keyCode == 13) {handlerButton(#{scroll_test.id},scroll_test)}"}%></td>
            <td class="field"><%= f.text_field :author, {:onkeyup=>"if (event.keyCode == 13) {handlerButton(#{scroll_test.id},scroll_test)}"}%></td>
            <td class="field"><%= f.text_field :body, {:onkeyup=>"if (event.keyCode == 13) {handlerButton(#{scroll_test.id},scroll_test)}"}%></td>
          </tr>
        <% end %>
        <% end %>
      </tbody>
    </table>

    <br>
  </div>
</body>

app/views/scroll_tests/index.js.erb
# app/views/posts/index.js.erb
$("#posts").append("<tbody class='page'><%= escape_javascript(render(@scroll_tests)) %></tbody>");

app/views/scroll_tests/new.html.erb
<h1>New scroll_test</h1>

<%= render 'form' %>

<%= link_to 'Back', scroll_tests_path %>

app/views/scroll_tests/show.html.erb
<div>
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @scroll_test.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @scroll_test.author %>
</p>

<p>
  <strong>Body:</strong>
  <%= @scroll_test.body %>
</p>

<%= link_to 'Edit', edit_scroll_test_path(@scroll_test) %> |
<%= link_to 'Back', scroll_tests_path %>
</div>

app/views/welcome/index.html.erb
<body>

  
  <div class="row first">
    <div class="large-3 columns">
      <h1><img src='/serve_image/graffitilogofenrir.jpg'/></h1>
    </div>
    <div class="large-9 columns">
      <ul class="inline-list right" >
        <li><a href="loki">Loki</a></li>
        <li><a href="heatmap">Heatmaps</a></li>
        <li><a href="#">Alerts</a></li>
        <li><a href="automated_feedback">Automated Feedback System</a></li>
        <li><a href="scroll_tests">Scrolling Test</a></li>
      </ul>
    </div>
  </div>
  
   
  
  
  <div class="row">    
    
     
     
    <div class="large-9 push-3 columns">
      
      <h3>Fenrir Toolkit <small>Home</small></h3>
      
      <p>Fenrir is a collection of demonstration kits.</p>
 
      <p>It will eventually house demonstration for a Loki GUI and for the Heatmaps program, in addition to suggestion layouts for customer interaction with the alerts system.</p>
             
    </div>
    
    
     
     
    <div class="large-3 pull-9 columns">
      
      <ul class="side-nav">
        <li><a href="#">Section 1</a></li>
        <li><a href="#">Section 2</a></li>
        <li><a href="#">Section 3</a></li>
        <li><a href="#">Section 4</a></li>
        <li><a href="#">Section 5</a></li>
        <li><a href="#">Section 6</a></li>
      </ul>
      
      <p><img src='/serve_image/graffiti.jpg'/></p>
        
    </div>
    
  </div>
    
  
   
  
  <footer class="row">
    <div class="large-12 columns">
      <hr/>
      <div class="row">
        <div class="large-6 columns">
          <p>And one by one back in the closet lays</p>
        </div>
        <div class="large-6 columns">
          <ul class="inline-list right">
            <li><a href="#">Section 1</a></li>
            <li><a href="#">Section 2</a></li>
            <li><a href="#">Section 3</a></li>
            <li><a href="#">Section 4</a></li>
          </ul>
        </div>
      </div>
    </div> 
  </footer>

   
</body>